version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: flask run --host=0.0.0.0 --port=5001
    volumes:
      - .:/app
    ports:
      - "5001:5001"
    environment:
      - FLASK_CONFIG=${FLASK_CONFIG}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEV_DB_URI=${DEV_DB_URI}
      - TEST_DB_URI=${TEST_DB_URI}
      - PROD_DB_URI=${PROD_DB_URI}
      - PORT=5001
    depends_on:
      - redis
