# version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  web:
    build:
      context: ./.docker
      dockerfile: Dockerfile.dev
    command: python run.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_CONFIG=${FLASK_CONFIG}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis
