FROM python:3.11-slim

WORKDIR /app

ENV POETRY_VIRTUALENVS_CREATE=false \
    POETRY_NO_INTERACTION=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir poetry==2.3.4

COPY pyproject.toml poetry.lock /app/
RUN poetry install --only main

COPY . /app

EXPOSE 5001

ENV FLASK_CONFIG=ProductionConfig
ENV PORT=5001

CMD ["gunicorn", "--bind", "0.0.0.0:5001", "run:app"]
