# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Install any needed packages specified in requirements.txt
COPY dev-requirements.txt /app/
RUN pip install --no-cache-dir -r dev-requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV FLASK_APP=run.py
ENV FLASK_ENV=testing
ENV FLASK_CONFIG=TestConfig

# Run pytest
CMD ["pytest", "-v"]
