FROM python:3.11-slim

WORKDIR /app

ENV POETRY_VIRTUALENVS_CREATE=false \
    POETRY_NO_INTERACTION=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir poetry==2.3.4

COPY pyproject.toml poetry.lock /app/
RUN poetry install --only main,dev

COPY . /app

EXPOSE 5001

ENV FLASK_APP=run.py
ENV FLASK_ENV=development
ENV FLASK_CONFIG=DevelopmentConfig

CMD ["flask", "run", "--host=0.0.0.0", "--port=5001"]
