FROM python:3.11-slim

WORKDIR /app

ENV POETRY_VIRTUALENVS_CREATE=false \
    POETRY_NO_INTERACTION=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir poetry==1.8.3

COPY pyproject.toml poetry.lock /app/
RUN poetry install --only main,dev

COPY . /app

EXPOSE 5001

ENV FLASK_APP=run.py
ENV FLASK_CONFIG=TestingConfig

CMD ["pytest", "-v"]
